{% set name = "salem" %}
{% set version = "0.3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/salem-{{ version }}.tar.gz
  sha256: 81ca57d402d3441cf722dff66b4566cd56917c16e2d5fef837a82e75bdc211d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - joblib
    - netCDF4
    - numpy
    - pandas
    - pyproj
    - scipy
    - six
    - xarray

test:
  imports:
    - salem
    - salem.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://salem.readthedocs.io
  summary: Geoscientific data I/O and map projections
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - fmaussion
    - TimoRoth
    - raybellwaves
