{% set name = "salem" %}
{% set version = "0.3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/salem-{{ version }}.tar.gz
  sha256: 26574b9f9e3b6bb0a6423f3d0aa697e6d659e0916afc8010b07e7d578523e34a

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - joblib
    - netCDF4
    - numpy
    - pandas
    - pyproj
    - scipy
    - six
    - xarray

test:
  imports:
    - salem
    - salem.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://salem.readthedocs.io
  summary: Geoscientific data I/O and map projections
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - fmaussion
    - TimoRoth
    - raybellwaves
